# -*- coding: utf-8 -*-
"""PYTHON DÖNEM ÖDEVİ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ULdm7lpBbttD5686e7B1_lVnaMlmMrwb
"""

# 1. Metin (String) tipi: Çift tırnak içinde yazılır.
ad_soyad = "Tarık Doğan"

# 2. Ondalıklı Sayı (Float) tipi: Virgül yerine nokta (.) kullanılır.
aylik_ucret = 549.90

# 3. Tam Sayı (Integer) tipi: Direkt sayı olarak yazılır.
sadakat_ayi = 28

# 4. Mantıksal (Boolean) tip: Sadece True (Doğru) veya False (Yanlış) değerini alır.
aktif_mi = True

# 5 farklı hizmeti içeren bir Liste
hizmetler = ["İnternet", "Televizyon", "Mobil Veri", "Sabit Telefon", "Bulut Depolama"]

# Müşteri bilgilerini içeren bir Sözlük
musteri_sozlugu = {
    "ad_soyad": ad_soyad,
    "aylik_ucret": aylik_ucret,
    "sadakat_ayi": sadakat_ayi,
    "aktif_mi": aktif_mi
}

# Az önce tanımlanan değişkenler buraya çekildi.

# Müşteri sözlüğündeki verileri kullanarak karar veriyoruz
if musteri_sozlugu["aylik_ucret"] > 500 or musteri_sozlugu["sadakat_ayi"] > 24:
    print("VIP Müşteri: İndirim Tanımla")
else:
    print("Standart Müşteri")

import random

# 1. İsmi Büyük Harfe Çevirme
# .upper() fonksiyonu string içindeki tüm karakterleri BÜYÜK harf yapar.
ad_buyuk = musteri_sozlugu["ad_soyad"].upper()

# 2. Rastgele Bir Sayı Üretme
# 1000 ile 9999 arasında rastgele bir tam sayı seçiyoruz.
rastgele_sayi = random.randint(1000, 9999)

# 3. CustomerID Oluşturma (f-string yöntemiyle)
# 'f' harfi tırnak içindeki süslü parantezlerin { } içine değişken koymamızı sağlar.
customerID = f"IST-2026-{rastgele_sayi}"

# Sonuçları görelim
print(f"Düzenlenmiş İsim: {ad_buyuk}")
print(f"Oluşturulan Müşteri ID: {customerID}")

# 5 farklı müşteri için sözlüklerden oluşan bir liste oluşturuyoruz
musteriler_listesi = [
    {
        "ad_soyad": "Fatih Eroğlu",
        "aylik_ucret": 550.0,
        "sadakat_ayi": 30,
        "aktif_mi": True
    },
    {
        "ad_soyad": "Simge Polat",
        "aylik_ucret": 420.0,
        "sadakat_ayi": 12,
        "aktif_mi": True
    },
    {
        "ad_soyad": "Cüneyt Çakır",
        "aylik_ucret": 600.0,
        "sadakat_ayi": 48,
        "aktif_mi": False
    },
    {
        "ad_soyad": "Seren Serengil",
        "aylik_ucret": 350.0,
        "sadakat_ayi": 5,
        "aktif_mi": True
    },
    {
        "ad_soyad": "Selahattin Çakaler",
        "aylik_ucret": 750.0,
        "sadakat_ayi": 25,
        "aktif_mi": True
    }
]

# Listenin başarıyla oluşturulduğunu kontrol etmek için uzunluğunu yazdıralım
print(f"Toplam müşteri sayısı: {len(musteriler_listesi)}")

# Fonksiyon
def tutar_hesapla(aylik_ucret):
    """
    Parametre olarak gelen ücrete %20 KDV ekler.
    """
    kdv_dahil_tutar = aylik_ucret * 1.20
   # %20 eklemek demek 1.20 ile çarpmak demektir
    return kdv_dahil_tutar

# Fonksiyon testi  (Örn: 100 TL için sonuç 120.0 olmalı)
test_tutari = 100
sonuc = tutar_hesapla(test_tutari)
print(f"Test Sonucu: 100 TL -> {sonuc} TL (KDV Dahil)")

import math      # Yuvarlama işlemleri için
import datetime  # Tarih bilgisi için

# Örnek bir müşteri ücreti alalım (Önceki listeden veya rastgele)
orijinal_ucret = 550.45

# 1. Daha önce yazdığımız fonksiyonu kullanarak KDV'li tutarı hesaplayalım
kdv_li_tutar = tutar_hesapla(orijinal_ucret) # Sonuç örn: 660.54

# 2. math kütüphanesi ile YUKARI yuvarlama
# math.ceil() fonksiyonu sayıyı ne olursa olsun bir üst tam sayıya tamamlar.
toplam_fatura = math.ceil(kdv_li_tutar)

# 3. datetime kütüphanesi ile bugünün tarihini alma
bugun = datetime.datetime.now()
tarih_formati = bugun.strftime("%d/%m/%Y") # Gün/Ay/Yıl formatına çevirdik

# Sonuçları Yazdıralım
print(f"KDV Dahil Ham Tutar: {kdv_li_tutar:.2f} TL")
print(f"Yuvarlanmış Toplam Fatura: {toplam_fatura} TL")
print("-" * 30)
print(f"Fatura Tarihi: {tarih_formati}")

# 1. Tekrarlı hizmetlerin olduğu liste (Bazı hizmetler bilerek birden fazla yazıldı)
tum_verilen_hizmetler = [
    "İnternet", "Televizyon", "İnternet",
    "Mobil Veri", "Televizyon", "Bulut Depolama",
    "İnternet", "Sabit Telefon", "Mobil Veri"
]

# 2. set() fonksiyonu ile benzersiz olanları bulma
# set yapısı, matematiksel kümeler gibidir;
#içinde bir elemandan sadece bir tane barındırır.
benzersiz_hizmetler = set(tum_verilen_hizmetler)

# 3. Sonuçları ekrana basma
print("Tüm Hizmet Kayıtları (Tekrarlı):", tum_verilen_hizmetler)
print("-" * 30)
print("Benzersiz Hizmet Listesi:", benzersiz_hizmetler)

# tekrar listeye çevirme
benzersiz_liste = list(benzersiz_hizmetler)

# AI TARAFINDAN HAZIRLANMIŞ VE DERLENMİŞ KOD #
import random    # Kütüphane Kullanımı (Rastgele Sayı)
import math      # Kütüphane Kullanımı (Matematiksel İşlemler)
import datetime  # Kütüphane Kullanımı (Zaman ve Tarih)

# --- 1. KISIM: TEMEL MANTIK ---

# Değişken Tanımlama ve Veri Tipleri (String, Float, Int, Boolean)
ad_soyad = "Ahmet Yılmaz"
aylik_ucret = 550.0
sadakat_ayi = 30
aktif_mi = True

# Liste Kullanımı (Veri Yapıları)
hizmetler = ["İnternet", "Televizyon", "Mobil Veri", "Sabit Telefon", "Bulut Depolama"]

# Sözlük (Dictionary) Kullanımı (Veri Yapıları)
musteri_verisi = {
    "ad_soyad": ad_soyad,
    "aylik_ucret": aylik_ucret,
    "sadakat_ayi": sadakat_ayi,
    "aktif_mi": aktif_mi
}

# Koşullu İfadeler ve Mantıksal Operatörler (If-Else / Or)
if musteri_verisi["aylik_ucret"] > 500 or musteri_verisi["sadakat_ayi"] > 24:
    status = "VIP Müşteri: İndirim Tanımla" # Koşul sağlanırsa çalışır
else:
    status = "Standart Müşteri" # Koşul sağlanmazsa çalışır

# String Metotları (Büyük Harfe Çevirme)
ad_buyuk = musteri_verisi["ad_soyad"].upper()

# Random Kütüphanesi ve String Formatlama (f-string)
customerID = f"IST-2026-{random.randint(1000, 9999)}"

# --- 2. KISIM: İLERİ SEVİYE YAPI ---

# Liste İçinde Sözlük Yapısı (Karmaşık Veri Yapıları)
musteriler_listesi = [
    {"ad": "Ahmet", "ucret": 550, "sure": 30},
    {"ad": "Ayşe", "ucret": 420, "sure": 12},
    {"ad": "Mehmet", "ucret": 600, "sure": 45}
]

# Fonksiyon Tanımlama (Parametre ve Return Kullanımı)
def tutar_hesapla(ucret):
    return ucret * 1.20 # %20 KDV ekleyip geri döndürme

# math Kütüphanesi Kullanımı (Yukarı Yuvarlama)
toplam_fatura = math.ceil(tutar_hesapla(musteri_verisi["aylik_ucret"]))

# datetime Kütüphanesi Kullanımı (Tarih Formatlama)
tarih = datetime.datetime.now().strftime("%d-%m-%Y")

# Set (Küme) Kullanımı (Benzersiz Eleman Bulma / Veri Temizleme)
tekrarlı_hizmetler = ["İnternet", "TV", "İnternet", "Mobil"]
benzersiz_hizmetler = set(tekrarlı_hizmetler)

# Çıktı Alma (Ekran Yazdırma)
print(f"ID: {customerID} | Müşteri: {ad_buyuk} | Durum: {status}")
print(f"Fatura Tutarı (KDV Dahil): {toplam_fatura} TL | Tarih: {tarih}")
print(f"Hizmet Çeşitleri: {benzersiz_hizmetler}")